version: "3.1"
services:
    app:
        build:
            context: .
        volumes:
          - .:/app
        ports:
            - "8080:8080"
        environment:
            WEATHER_API_TOKEN: $WEATHER_API_TOKEN
        dns:
            - 8.8.8.8

    app-tests:
        build:
            dockerfile: Dockerfile.tests
            context: .
        volumes:
          - .:/app
        environment:
            WEATHER_API_TOKEN: "api-token-mocked"