version: "3.1"
services:
    jaeager-all-in-one:
        image: jaegertracing/all-in-one:latest
        restart: always
        ports:
            - "16686:16686"
            - "14268"
            - "14250"
    phometheus:
        image: prom/prometheus:latest
        restart: always
        volumes:
            - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yaml
        ports:
            - "9090:9090"
    otel-collector:
        image: otel/opentelemetry-collector:latest
        restart: always
        command: ["--config", "/etc/otel-collector-config.yaml"]
        volumes:
            - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "8888:8888"
            - "8889:8889"
            - "4317:4317"
    app:
        build:
            context: .
        volumes:
          - .:/app
        ports:
            - "8080:8080"
        environment:
            WEATHER_API_TOKEN: $WEATHER_API_TOKEN
        dns:
            - 8.8.8.8
        depends_on:
            - jaeager-all-in-one
            - phometheus
            - otel-collector